dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - ng test

addons:
  chrome: stable

cache:
  directories:
     - node_modules
